using System.Collections.Generic;

namespace MIG.DataStuff
{
    public abstract class Names
    {
        public enum Genres
        {
            LofiHipHop, Acoustic, Country, RockMetal, Trap,
            Pop,
            BigRoom, SpinninRecords, Bootleg, Bounce, MelbourneBounce,
            Drumstep, DnB,
            Dubstep, MelodicDubstep,
            FutureBass, FutureFunk, FutureHouse, FutureBounce,
            Electro, ElectroSwing,
            GeneralEDM, EDMTrap, Electrio,
            HandsUp, EuroDance,
            HardBass, Speedcore,
            Dreamy, Euphoric, RawEuphoric, NastyEuphoric,
            Rawstyle, PsychedelicRawstyle, Hardcore, Uptempo, Frenchcore,
            HappyHardcore, Psytrance, Trance,
            AimbottzHouse, DeepHouse, House, 
            ProgressiveHouse, ProgressiveDream, ProgressivePop, NCS, 
            ElectroHouse, TakingElectroLiteral, 
            Dudududu, MelodicHouse, TropicalHouse,
            Downtempo, Synthwave
        }
        public static List<string> BannedWords { get; } = new()
        {
            "devi",
            "er",
            "jorden",
            "rd.",
            "dem",
            "john",
            "collin",
            "matthew",
            "pnb",
            "feat.",
            "sko",
            "danyka",
            "capone",
            "fejrer",
            "uma",
            "jonny",
            "chiyoko",
            "thnks",
            "fr",
            "th",
            "mmrs",
            "pa",
            "wa",
            "zoe",
            "johnny",
            "cuore",
            "ghiacciato",
            "thie",
            "vs",
            "Ku'",
            "rita",
            "handzup",
            "faidherbe",
            "harri",
            "cozi",
            "defi",
            "cascada",
            "vs.",
            "mou",
            "emmaaa",
            "niya",
            "boten",
            "fugazi",
            "mtc",
            "mtc2",
            "roseanna",
            "titsepoken",
            "avem",
            "/",
            "brenton",
            "aloma",
            "mixie",
            "kayliana",
            "hotto",
            "kyoto",
            "b0y",
            "dine",
            "næ",
            "jp",
            "ta'",
            "d.",
            "myten",
            "ma,",
            "halve",
            "conrad",
            "na",
            "richard",
            "al",
            "nese",
            "kat",
            "aviation",
            "anna",
            "dutchman",
            "op",
            "-",
            "la",
            "bangarang",
            "alan",
            "nicktim",
            "pika",
            "theos",
            "maren",
            "da",
            "andrew",
            "sætran",
            "cascada,",
            "tinie",
            "dota",
            "lofi",
            "laura",
            "romero",
            "promiseland",
            "n",
            "'n'",
            "emi",
            "mc",
            "technobase.fm",
            "ellie",
            "pt.",
            "sætran,",
            "pt.",
            "være",
            "det",
            "movie",
            "ku'",
            "dj",
            "de",
            "m.o.a.b",
            "r4v3",
            "video"
        };
    }
}